class BilibiliOcr{constructor(props){this.props=props;this.data={img:{primaryWidth:324,primaryHeight:324,width:260,height:260,countAvg:80,countStart:2,countEnd:20,recWidth:50,bigDataMax:7000,dupImpurityValue:200,recWidthAgain:80,diff:60,continuityDiff:15,posDiff:30,canvas:"",ctx:"",bigData:[],imageData:{},oldImageData:{},recData:[],colorArr:[],...props.imm},verImg:{width:116,height:40,verImgX:0,verImgY:344,canvas:"",ctx:"",imageData:{},num:0,textArr:[],...props.verImg},pos:{width:25}};this.call={success:()=>{},fail:()=>{}};this.init();}
init(){this.verImgInit();}
verImgInit(){const img=new Image();const _this=this;let{canvas,ctx,width,height,verImgX,verImgY}=this.data.verImg;img.crossOrigin="Anonymous";img.src=this.props.url;img.onload=function(){canvas=document.createElement("canvas");ctx=canvas.getContext("2d");canvas.width=width;canvas.height=height;ctx.drawImage(this,verImgX,verImgY,width,height,0,0,width,height);_this.data.verImg.canvas=canvas;_this.data.verImg.ctx=ctx;_this.verImgHandle();};}
verImgHandle(){const num=this.checkNumber();this.data.verImg.num=num;console.log("当前字个数为：",num);if(num>3){console.warn("识别数字大于3，跳过");this.call.fail();return;}
const arr=this.textPix();console.log("校验字体像素点为：",arr);this.data.verImg.textArr=arr;this.imgInit();}
imgInit(){const{width,height,primaryWidth,primaryHeight}=this.data.img;const img=new Image();const _this=this;img.crossOrigin="Anonymous";img.src=this.props.url;img.onload=function(){const canvas=document.createElement("canvas");const ctx=canvas.getContext("2d");canvas.width=width;canvas.height=height;ctx.drawImage(this,10,10,primaryWidth,primaryHeight,0,0,width,height);_this.data.img.canvas=canvas;_this.data.img.ctx=ctx;_this.imgHandle();};}
imgHandle(){let{width,height,ctx}=this.data.img;this.data.img.imageData=ctx.getImageData(0,0,width,height);this.data.img.oldImageData=JSON.parse(JSON.stringify(this.data.img.imageData));this.grayscale();this.pixels();this.recHandle();this.recRender();this.computePix();this.posRender();}
pixels(){const{imageData,countAvg,countStart,countEnd}=this.data.img;const _this=this;let data=imageData.data;let preVal,nowVal,isBig,bigCount=0,bigData=[];for(let i=0,j=0;i<data.length;i+=4,j+=4){if(!preVal){preVal=data[i];if(!nowVal){continue;}}
nowVal=data[i];if(Math.abs(preVal-nowVal)>countAvg&&bigCount<countEnd){bigCount++;bigData.push(i);}else{bigCount=0;bigData=[];preVal=data[i];}
if(bigCount>countStart&&bigCount<countEnd){for(let _i=0;_i<bigData.length;_i++){data[bigData[_i]]=0;data[bigData[_i]+1]=255;data[bigData[_i]+2]=0;_this.data.img.bigData.push(bigData[_i]);}
bigData=[];}}
this.data.img.ctx.putImageData(imageData,0,0);}
recHandle(recWidth=this.data.img.recWidth){const{imageData,width,bigDataMax,dupImpurityValue}=this.data.img;const nextCol=width*4;let data=imageData.data;let bigData=this.data.img.bigData;let newBigData=[];let recData=[];let recDataAvg;if(bigData.length>bigDataMax){console.warn(`捕获到超出${bigDataMax}的像素点，过于复杂不计算`,bigData.length);this.call.fail();return;}
if(!bigData.length){console.warn("无像素点捕获，退出");this.call.fail();return;}
for(let i=0;i<bigData.length;i++){let line=bigData[i]-parseInt(recWidth/2)*(nextCol-recWidth*4);if(line<=0){line=bigData[i]-parseInt(recWidth/2)*4;}
if(nextCol-(line%nextCol)<=recWidth*4){line+=recWidth*4-(nextCol-(line%nextCol));}
if(nextCol-(line%nextCol)<=recWidth*4){line-=recWidth*4-(nextCol-(line%nextCol));}
recData.push({data:[],val:0,bigDataKey:i,sum:0});for(let j=0;j<recWidth;j++){let j_s=line+j*nextCol;let j_e=line+j*nextCol+recWidth*4;for(let z=j_s;z<j_e;z+=4){if(data[z+1]===255){recData[i].data.push(z);recData[i].sum++;}}}
recData[i].val=line;}
recData=recData.sort(this.compare("sum"));recData=this.dupRemoval(recData);recData=this.dupImpurity(recData,dupImpurityValue);console.log("一共点数：",bigData.length);console.log("降噪后值，取前六名：",recData);recData.map(item=>{item.data.map(items=>{data[items]=255;data[items+1]=0;data[items+2]=0;newBigData.push(items);});});this.data.img.ctx.putImageData(imageData,0,0);this.data.img.recData=recData;this.data.img.bigData=newBigData;console.log("捕获点数：",newBigData.length);}
recRender(recWidth=this.data.img.recWidthAgain){const{bigData,width,recData,imageData,ctx,canvas}=this.data.img;const nextCol=width*4;let data=imageData.data;let recRenderData=[];for(let i=0;i<recData.length;i++){let line=recData[i].val-15*nextCol-15*4;if(line<0){line=recData[i].val;}
recData[i].recRenderData=[];for(let j=0;j<recWidth;j++){let j_s=line+j*nextCol;let j_e=line+j*nextCol+recWidth*4;for(let z=j_s;z<j_e;z+=4){data[z+3]=100;recData[i].recRenderData.push(z);}}}
this.data.img.ctx.putImageData(imageData,0,0);}
rezCanvas(){const{imageData,oldImageData}=this.data.img;let data=imageData.data;let oldData=oldImageData.data;for(let i=0;i<data.length;i+=4){data[i]=oldData[i];data[i+1]=oldData[i+1];data[i+2]=oldData[i+2];}
this.data.img.ctx.putImageData(imageData,0,0);}
computePix(){const{recData,imageData,diff,width,height,continuityDiff}=this.data.img;let data=imageData.data;let colorArr=[];let sortArr=[];recData.map((item,i)=>{colorArr.push({key:i,data:[],colorMax:0,recRenderData:item.recRenderData,sum:0,x:0,y:0,xyCenter:0,chooseNo:0});item.data.map(val=>{colorArr[i].data.push(data[val]);});colorArr[i].colorMax=this.colorMax(colorArr[i].data);});colorArr.map((item,_i)=>{item.recRenderData.map(i=>{if(Math.abs(data[i]-item.colorMax)<diff){item.sum++;data[i]=255;data[i+1]=0;data[i+2]=0;}});this.recRenderDataFilter(item,data,"longRec",continuityDiff*4,continuityDiff*width,continuityDiff);this.recRenderDataFilter(item,data,"heightRec",continuityDiff,continuityDiff*width*2*2,continuityDiff);if(item.recRenderData.length%2===0){item.xyCenter=item.recRenderData[item.recRenderData.length/2+
Math.sqrt(item.recRenderData.length)/2];}else{item.xyCenter=item.recRenderData[parseInt(item.recRenderData.length/2)];}
item.x=((item.xyCenter/4)%width)-10;item.y=(item.xyCenter/4-item.x)/width-10;});sortArr=JSON.parse(JSON.stringify(colorArr)).sort(this.compare("sum"));sortArr.map((item,i)=>{colorArr.find(items=>{if(item.key===items.key){items.chooseNo=i;return true;}});});this.data.img.ctx.putImageData(imageData,0,0);this.data.img.colorArr=colorArr;console.log(colorArr);}
recRenderDataFilter(item,data,type,diffILen,diffJLen,continuityDiff){const{width,imageData}=this.data.img;let recRenderDataHandle=[];let _sum=0;item.recRenderData.map((__i,index)=>{for(let j=__i;j<__i+diffILen;j+=4){for(let z=j;z<j+diffJLen;z+=4*width){if(data[z]===255){_sum++;recRenderDataHandle.push(__i);}else{_sum=0;recRenderDataHandle=[];break;}}}
if(_sum>=continuityDiff*6){recRenderDataHandle.map(___i=>{data[___i]=0;data[___i+1]=255;data[___i+2]=0;});item.sum--;_sum=0;recRenderDataHandle=[];}});}
posRender(diff=this.data.img.posDiff,txAlArr=[],colorAlArr=[]){const{colorArr}=this.data.img;const{textArr}=this.data.verImg;const pos=this.data.pos;textArr.map(item=>{if(textArr.length===colorArr.length){colorArr.find(items=>{if(items.chooseNo===item.chooseNo){const dom=document.createElement("div");dom.className="pos";dom.innerText=item.key+1;dom.style.height=dom.style.width=pos.width+"px";dom.style.left=items.x+"px";dom.style.top=items.y+"px";dom.style.visibility="hidden";dom.style.position="absolute";this.props.el&&this.props.el.appendChild(dom);setTimeout(()=>{this.call.success(item.key,this.getOffsetLeft(dom)+pos.width/2,this.getOffsetTop(dom)+pos.width/2,item.key===textArr.length-1);},item.key*200);txAlArr.push(item.key);return true;}});return;}
if(txAlArr.includes(item.key)){return;}
colorArr.find(items=>{if(colorAlArr.includes(items.key)){return;}
if(Math.abs(items.sum-item.val)<diff){const dom=document.createElement("div");dom.className="pos";dom.style.height=dom.style.width=pos.width+"px";dom.style.left=items.x+"px";dom.style.top=items.y+"px";dom.style.visibility="hidden";dom.style.position="absolute";dom.innerText=item.key+1;this.props.el&&this.props.el.appendChild(dom);setTimeout(()=>{this.call.success(item.key,this.getOffsetLeft(dom)+pos.width/2,this.getOffsetTop(dom)+pos.width/2,item.key===textArr.length-1);},item.key*200);txAlArr.push(item.key);colorAlArr.push(items.key);return true;}});});if(txAlArr.length<textArr.length){this.posRender(diff+30,txAlArr,colorAlArr);}}
colorMax(arr){let data={};let newArr=[];arr.map(val=>{if(data[val+""]>=0){data[val+""]++;return;}
data[val+""]=0;});let max={key:0,val:0};newArr=Object.keys(data);if(newArr.length>10){for(let i=0;i<newArr.length/2;i++){delete data[newArr[i]];}}
Object.keys(data).map(key=>{if(data[key]>max.val){max={key,val:data[key]};}});return max.key;}
textPix(){const{num,width}=this.data.verImg;const mid=parseInt(width/4/2)*4;let arr=[];let sortArr=[];if(num===3){arr.push({key:0,val:this.isCheckThickness(mid+parseInt(width/4)*4-4,width,mid+parseInt(width/4)*4,true)},{key:1,val:this.isCheckThickness(mid+(width/2)*4,width,width,true)},{key:2,val:this.isCheckThickness(width*4-4,width,mid+parseInt(width/4)*4,true)});}else{arr.push({key:0,val:this.isCheckThickness(parseInt(width/2)*4-4,width,parseInt(width/2)*4,true)},{key:1,val:this.isCheckThickness(width*4-4,width,parseInt(width/2)*4,true)});}
sortArr=JSON.parse(JSON.stringify(arr)).sort(this.compare("val"));sortArr.map((item,i)=>{arr.find(items=>{if(item.key===items.key){items.chooseNo=i;return true;}});});return arr;}
checkNumber(){let{canvas,width,ctx}=this.data.verImg;let imageData=ctx.getImageData(0,0,canvas.width,canvas.height);let data=imageData.data;const mid=parseInt(width/4/2)*4;this.data.verImg.imageData=imageData;let isL1=this.isCheckThickness(mid,width);let isL2=this.isCheckThickness(mid+parseInt(width/4)*4,width);let isL3=this.isCheckThickness(mid+(width/2)*4,width);let isL4=this.isCheckThickness(mid*3+(width/2)*4,width);let isL5=this.isCheckThickness(mid*2+(width/2)*2,width);if(isL1&&isL2&&isL3&&isL4){return 4;}
else if(!isL5){return 2;}
return 3;}
isCheckThickness(mid,width,fine=3,isSum=false){let{imageData}=this.data.verImg;const data=imageData.data;let isTrue=false;let sum=0;for(let i=mid;i<data.length;i+=width*4){for(let j=0;j<fine;j+=4){let _i=i-j;if(data[_i]<200){if(isSum){sum++;}else{return true;}}}}
this.data.verImg.ctx.putImageData(imageData,0,0);if(isSum){return sum*3;}
return isTrue;}
grayscale(){const{imageData}=this.data.img;let data=imageData.data;for(let i=0;i<data.length;i+=4){let avg=(data[i]+data[i+1]+data[i+2])/3;data[i]=avg;data[i+1]=avg;data[i+2]=avg;}
this.data.img.ctx.putImageData(imageData,0,0);}
dupRemoval(data){let dupArr=[];return data.map(item=>{let newItem=[];item.data.map(val=>{if(!dupArr.includes(val)){dupArr.push(val);newItem.push(val);}else{item.sum--;}});return{...item,data:newItem};});}
dupImpurity(data,val){const{num}=this.data.verImg;let newData=[];data.map(item=>item.sum>=val&&newData.push(item));if(newData.length<num){return this.dupImpurity(data,val-10);}
return newData;}
compare(property){return(now,next)=>{let val1=now[property];let val2=next[property];return val2-val1;};}
getOffsetTop(el){let top=el.offsetTop;let parent=el.offsetParent;while(parent){top+=parent.offsetTop;parent=parent.offsetParent;}
return top;}
getOffsetLeft(el){let left=el.offsetLeft;let parent=el.offsetParent;while(parent){left+=parent.offsetLeft;parent=parent.offsetParent;}
return left;}
on(key,fn){if(this.call[key]){this.call[key]=fn;}}}
const autoBilibiliOcr=()=>{setTimeout(()=>{if(document.querySelector(".geetest_panel_error").style.display!=="none"){document.querySelector(".geetest_panel_error_content").click();autoBilibiliOcr();return;}
if(document.querySelector(".geetest_panel_next").style.display==="none"){return;}
var Ocr=new BilibiliOcr({url:document.querySelector(".geetest_item_img").src,el:document.querySelector(".geetest_item_wrap")});Ocr.on("success",(key,x,y,isEnd)=>{console.log(key,x,y);var evt=document.createEvent("MouseEvents");evt.initMouseEvent("click",true,false,null,0,0,0,x-135,y-180,false,false,false,false,0,null);document.querySelector(".geetest_item_wrap").dispatchEvent(evt);if(isEnd){document.querySelector(".geetest_commit").click();setTimeout(()=>{if(document.querySelector(".geetest_result_tip.geetest_up.geetest_fail")){setTimeout(()=>{autoBilibiliOcr();},1500+parseInt(Math.random()*1000));return;}},500);}});Ocr.on("fail",()=>{document.querySelector(".geetest_refresh").click();console.log("fail");autoBilibiliOcr();});},800+parseInt(Math.random()*1000));};autoBilibiliOcr()